name: CustomVersionSeedCommand
version: ${project.version}
main: de.flashyboi.minecraft.plugins.customversionseedcommand.CustomVersionSeedCommand
api-version: 1.17
authors: [ flash_btw ]
description: shows a configurable message at /version and /seed
website: http://gammellounge.de

commands:
  CustomVersionSeedCommand:
    description: "the main command of the plugin 'CustomVersionSeedCommand'"
    aliases: [customvscommand, cvsc]

permissions:
  CustomVersionSeedCommand.original.versioncommand:
    description: "allows the player to see the actual bukkit version command"
  CustomVersionSeedCommand.original.seedcommand:
    description: "allows the player to see the actual seed"
  CustomVersionSeedCommand.reload:
    description: "allow the player to reload the config"
  CustomVersionSeedCommand.allowtabcomplete:
    description: "allow the player to tabcomplete after /version and /seed"

